name: map_it
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


environment:
  sdk: '>=3.1.0-262.2.beta <4.0.0'

dependencies:
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  image_picker: ^0.8.5+3
  shared_preferences: ^2.0.15
  geolocator: ^9.0.2
  connectivity_plus: ^3.0.4
  permission_handler: ^10.2.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  lottie: ^2.4.0
  intl: ^0.18.0
  flutter_secure_storage: ^8.0.0
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/


